CREATE TABLE audit_project (
    id UUID PRIMARY KEY,
    name VARCHAR(200) NOT NULL,
    storage_path VARCHAR(1000) NOT NULL,
    repository_url VARCHAR(2000),
    default_branch VARCHAR(500),
    description VARCHAR(1000) NOT NULL DEFAULT '',
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    archived_at TIMESTAMP WITH TIME ZONE
);

CREATE TABLE audit_task (
    id UUID PRIMARY KEY,
    project_id UUID NOT NULL,
    status VARCHAR(40) NOT NULL,
    progress INTEGER NOT NULL,
    current_stage VARCHAR(200) NOT NULL,
    error_message VARCHAR(2000),
    base_commit_sha VARCHAR(64),
    target_commit_sha VARCHAR(64),
    merge_base_sha VARCHAR(64),
    change_summary TEXT,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    completed_at TIMESTAMP WITH TIME ZONE,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT fk_audit_task_project
        FOREIGN KEY (project_id) REFERENCES audit_project(id) ON DELETE CASCADE,
    CONSTRAINT chk_audit_task_current_status
        CHECK (status IN ('UPLOADED', 'MATERIALIZING', 'DIFFING', 'INVENTORY', 'INDEXING',
                          'RECON', 'AGENT_RECON', 'PLANNING', 'ANALYSIS', 'CRITIC_REVIEW',
                          'RESULT_VALIDATION', 'REPORTING', 'COMPLETED', 'FAILED', 'CANCELLED'))
);

CREATE TABLE code_chunk (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_id UUID NOT NULL,
    file_path VARCHAR(1000) NOT NULL,
    symbol_name VARCHAR(500),
    endpoint VARCHAR(500),
    start_line INTEGER NOT NULL,
    end_line INTEGER NOT NULL,
    content TEXT NOT NULL,
    chunk_type VARCHAR(40) NOT NULL DEFAULT 'TEXT',
    parameters TEXT NOT NULL DEFAULT '',
    annotations TEXT NOT NULL DEFAULT '',
    called_symbols TEXT NOT NULL DEFAULT '',
    change_type VARCHAR(30) NOT NULL DEFAULT 'UNCHANGED',
    analysis_scope VARCHAR(30) NOT NULL DEFAULT 'CONTEXT',
    base_content TEXT NOT NULL DEFAULT '',
    CONSTRAINT fk_code_chunk_task
        FOREIGN KEY (task_id) REFERENCES audit_task(id) ON DELETE CASCADE,
    CONSTRAINT chk_code_chunk_current_scope
        CHECK (analysis_scope IN ('CHANGED', 'IMPACTED', 'CONTEXT'))
);

CREATE TABLE finding (
    id UUID PRIMARY KEY,
    task_id UUID NOT NULL,
    type VARCHAR(50) NOT NULL,
    severity VARCHAR(20) NOT NULL,
    confidence VARCHAR(20) NOT NULL,
    title VARCHAR(500) NOT NULL,
    file_path VARCHAR(1000) NOT NULL,
    start_line INTEGER NOT NULL,
    end_line INTEGER NOT NULL,
    endpoint VARCHAR(500),
    description TEXT NOT NULL,
    evidence TEXT NOT NULL,
    remediation TEXT NOT NULL,
    delta_status VARCHAR(30) NOT NULL DEFAULT 'NEW',
    fingerprint VARCHAR(64) NOT NULL DEFAULT '',
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_finding_task
        FOREIGN KEY (task_id) REFERENCES audit_task(id) ON DELETE CASCADE,
    CONSTRAINT chk_finding_current_type
        CHECK (type IN ('AUTHORIZATION', 'SQL_INJECTION', 'SENSITIVE_INFORMATION_DISCLOSURE',
                        'STORED_XSS', 'VALIDATION_BYPASS')),
    CONSTRAINT chk_finding_current_delta
        CHECK (delta_status IN ('NEW', 'PERSISTING'))
);

CREATE TABLE agent_run (
    id UUID PRIMARY KEY,
    task_id UUID NOT NULL,
    agent_type VARCHAR(40) NOT NULL,
    target_chunk_id BIGINT,
    target_symbol VARCHAR(500),
    status VARCHAR(30) NOT NULL,
    step_count INTEGER NOT NULL DEFAULT 0,
    tool_call_count INTEGER NOT NULL DEFAULT 0,
    model_call_count INTEGER NOT NULL DEFAULT 0,
    summary TEXT,
    started_at TIMESTAMP WITH TIME ZONE NOT NULL,
    completed_at TIMESTAMP WITH TIME ZONE,
    CONSTRAINT fk_agent_run_task
        FOREIGN KEY (task_id) REFERENCES audit_task(id) ON DELETE CASCADE,
    CONSTRAINT fk_agent_run_chunk
        FOREIGN KEY (target_chunk_id) REFERENCES code_chunk(id) ON DELETE SET NULL,
    CONSTRAINT chk_agent_run_current_type
        CHECK (agent_type IN ('RECON', 'ORCHESTRATOR', 'SQL_INJECTION', 'AUTHORIZATION',
                              'SENSITIVE_INFORMATION', 'STORED_XSS', 'VALIDATION_BYPASS',
                              'CRITIC', 'REPORT'))
);

CREATE TABLE agent_event (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_id UUID NOT NULL,
    run_id UUID,
    agent_type VARCHAR(40) NOT NULL,
    event_type VARCHAR(40) NOT NULL,
    message TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_agent_event_task
        FOREIGN KEY (task_id) REFERENCES audit_task(id) ON DELETE CASCADE,
    CONSTRAINT fk_agent_event_run
        FOREIGN KEY (run_id) REFERENCES agent_run(id) ON DELETE CASCADE,
    CONSTRAINT chk_agent_event_current_type
        CHECK (agent_type IN ('RECON', 'ORCHESTRATOR', 'SQL_INJECTION', 'AUTHORIZATION',
                              'SENSITIVE_INFORMATION', 'STORED_XSS', 'VALIDATION_BYPASS',
                              'CRITIC', 'REPORT'))
);

CREATE TABLE audit_hypothesis (
    id UUID PRIMARY KEY,
    task_id UUID NOT NULL,
    run_id UUID NOT NULL,
    type VARCHAR(50) NOT NULL,
    status VARCHAR(40) NOT NULL,
    claim TEXT NOT NULL,
    primary_chunk_id BIGINT NOT NULL,
    evidence_chunk_ids TEXT NOT NULL,
    confidence VARCHAR(20) NOT NULL,
    critic_reason TEXT,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_hypothesis_task
        FOREIGN KEY (task_id) REFERENCES audit_task(id) ON DELETE CASCADE,
    CONSTRAINT fk_hypothesis_run
        FOREIGN KEY (run_id) REFERENCES agent_run(id) ON DELETE CASCADE,
    CONSTRAINT fk_hypothesis_chunk
        FOREIGN KEY (primary_chunk_id) REFERENCES code_chunk(id) ON DELETE CASCADE,
    CONSTRAINT chk_hypothesis_current_type
        CHECK (type IN ('AUTHORIZATION', 'SQL_INJECTION', 'SENSITIVE_INFORMATION_DISCLOSURE',
                        'STORED_XSS', 'VALIDATION_BYPASS'))
);

CREATE TABLE ai_report_summary (
    task_id UUID PRIMARY KEY,
    executive_summary TEXT NOT NULL,
    coverage_summary TEXT NOT NULL,
    generated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_ai_report_task
        FOREIGN KEY (task_id) REFERENCES audit_task(id) ON DELETE CASCADE
);

CREATE TABLE semantic_symbol (
    id UUID PRIMARY KEY,
    task_id UUID NOT NULL,
    chunk_id BIGINT,
    kind VARCHAR(40) NOT NULL,
    qualified_name VARCHAR(1500) NOT NULL,
    simple_name VARCHAR(500) NOT NULL,
    owner_name VARCHAR(1000),
    signature TEXT NOT NULL,
    return_type VARCHAR(1000),
    parameter_types TEXT NOT NULL,
    file_path VARCHAR(1000) NOT NULL,
    start_line INTEGER NOT NULL,
    end_line INTEGER NOT NULL,
    endpoint VARCHAR(500),
    annotations TEXT NOT NULL,
    details TEXT NOT NULL,
    CONSTRAINT fk_semantic_symbol_task
        FOREIGN KEY (task_id) REFERENCES audit_task(id) ON DELETE CASCADE,
    CONSTRAINT fk_semantic_symbol_chunk
        FOREIGN KEY (chunk_id) REFERENCES code_chunk(id) ON DELETE SET NULL
);

CREATE TABLE semantic_call_edge (
    id UUID PRIMARY KEY,
    task_id UUID NOT NULL,
    caller_symbol_id UUID NOT NULL,
    callee_symbol_id UUID,
    caller_chunk_id BIGINT,
    callee_chunk_id BIGINT,
    call_site_line INTEGER NOT NULL,
    called_name VARCHAR(500) NOT NULL,
    expression TEXT NOT NULL,
    edge_type VARCHAR(40) NOT NULL,
    confidence VARCHAR(20) NOT NULL,
    resolution_reason TEXT NOT NULL,
    argument_mapping TEXT NOT NULL,
    CONSTRAINT fk_semantic_edge_task
        FOREIGN KEY (task_id) REFERENCES audit_task(id) ON DELETE CASCADE,
    CONSTRAINT fk_semantic_edge_caller
        FOREIGN KEY (caller_symbol_id) REFERENCES semantic_symbol(id) ON DELETE CASCADE,
    CONSTRAINT fk_semantic_edge_callee
        FOREIGN KEY (callee_symbol_id) REFERENCES semantic_symbol(id) ON DELETE CASCADE,
    CONSTRAINT fk_semantic_edge_caller_chunk
        FOREIGN KEY (caller_chunk_id) REFERENCES code_chunk(id) ON DELETE SET NULL,
    CONSTRAINT fk_semantic_edge_callee_chunk
        FOREIGN KEY (callee_chunk_id) REFERENCES code_chunk(id) ON DELETE SET NULL
);

CREATE TABLE security_flow (
    id UUID PRIMARY KEY,
    task_id UUID NOT NULL,
    type VARCHAR(50) NOT NULL,
    source_symbol_id UUID,
    sink_symbol_id UUID,
    primary_chunk_id BIGINT NOT NULL,
    source_description TEXT NOT NULL,
    sink_description TEXT NOT NULL,
    guard_summary TEXT NOT NULL,
    path_text TEXT NOT NULL,
    evidence_chunk_ids TEXT NOT NULL,
    confidence VARCHAR(20) NOT NULL,
    confirmed_relation_edges INTEGER NOT NULL,
    local_semantic_gaps INTEGER NOT NULL,
    CONSTRAINT fk_security_flow_task
        FOREIGN KEY (task_id) REFERENCES audit_task(id) ON DELETE CASCADE,
    CONSTRAINT fk_security_flow_source
        FOREIGN KEY (source_symbol_id) REFERENCES semantic_symbol(id) ON DELETE SET NULL,
    CONSTRAINT fk_security_flow_sink
        FOREIGN KEY (sink_symbol_id) REFERENCES semantic_symbol(id) ON DELETE SET NULL,
    CONSTRAINT fk_security_flow_chunk
        FOREIGN KEY (primary_chunk_id) REFERENCES code_chunk(id) ON DELETE CASCADE,
    CONSTRAINT chk_security_flow_current_type
        CHECK (type IN ('AUTHORIZATION', 'SQL_INJECTION', 'SENSITIVE_INFORMATION_DISCLOSURE',
                        'STORED_XSS', 'VALIDATION_BYPASS'))
);

CREATE TABLE git_file_change (
    id UUID PRIMARY KEY,
    task_id UUID NOT NULL,
    old_path VARCHAR(1000),
    new_path VARCHAR(1000),
    change_type VARCHAR(30) NOT NULL,
    additions INTEGER NOT NULL,
    deletions INTEGER NOT NULL,
    old_ranges TEXT NOT NULL,
    new_ranges TEXT NOT NULL,
    context_text TEXT NOT NULL,
    configuration_change BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT fk_git_file_change_task
        FOREIGN KEY (task_id) REFERENCES audit_task(id) ON DELETE CASCADE
);

CREATE TABLE semantic_method_change (
    id UUID PRIMARY KEY,
    task_id UUID NOT NULL,
    change_kind VARCHAR(40) NOT NULL,
    method_name VARCHAR(500) NOT NULL,
    base_path VARCHAR(1000),
    target_path VARCHAR(1000),
    base_symbol VARCHAR(1500),
    target_symbol VARCHAR(1500),
    base_start_line INTEGER,
    base_end_line INTEGER,
    target_start_line INTEGER,
    target_end_line INTEGER,
    base_content TEXT NOT NULL,
    target_content TEXT NOT NULL,
    details TEXT NOT NULL,
    CONSTRAINT fk_semantic_method_change_task
        FOREIGN KEY (task_id) REFERENCES audit_task(id) ON DELETE CASCADE
);

CREATE INDEX idx_audit_project_archived_at ON audit_project(archived_at);
CREATE INDEX idx_audit_task_project_id ON audit_task(project_id);
CREATE INDEX idx_audit_task_created_at ON audit_task(created_at DESC);
CREATE INDEX idx_code_chunk_task_id ON code_chunk(task_id);
CREATE INDEX idx_finding_task_id ON finding(task_id);
CREATE INDEX idx_finding_task_severity ON finding(task_id, severity);
CREATE UNIQUE INDEX uq_finding_task_fingerprint ON finding(task_id, fingerprint);
CREATE INDEX idx_agent_run_task ON agent_run(task_id);
CREATE INDEX idx_agent_event_task_id ON agent_event(task_id, id);
CREATE INDEX idx_hypothesis_task ON audit_hypothesis(task_id, status);
CREATE INDEX idx_semantic_symbol_task ON semantic_symbol(task_id);
CREATE INDEX idx_semantic_symbol_qualified ON semantic_symbol(task_id, qualified_name);
CREATE INDEX idx_semantic_edge_caller ON semantic_call_edge(task_id, caller_symbol_id);
CREATE INDEX idx_semantic_edge_callee ON semantic_call_edge(task_id, callee_symbol_id);
CREATE INDEX idx_security_flow_task_type ON security_flow(task_id, type);
CREATE INDEX idx_security_flow_primary_chunk ON security_flow(task_id, primary_chunk_id);
CREATE INDEX idx_git_file_change_task ON git_file_change(task_id);
CREATE INDEX idx_git_file_change_target_path ON git_file_change(task_id, new_path);
CREATE INDEX idx_semantic_method_change_task_kind
    ON semantic_method_change(task_id, change_kind);
CREATE INDEX idx_semantic_method_change_target
    ON semantic_method_change(task_id, target_path, target_start_line);
CREATE INDEX idx_semantic_method_change_base
    ON semantic_method_change(task_id, base_path, base_start_line);
