CREATE TABLE audit_project (
    id UUID PRIMARY KEY,
    name VARCHAR(200) NOT NULL,
    original_filename VARCHAR(500) NOT NULL,
    storage_path VARCHAR(1000) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE audit_task (
    id UUID PRIMARY KEY,
    project_id UUID NOT NULL,
    status VARCHAR(40) NOT NULL,
    progress INTEGER NOT NULL,
    current_stage VARCHAR(200) NOT NULL,
    error_message VARCHAR(2000),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    completed_at TIMESTAMP WITH TIME ZONE,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT fk_audit_task_project
        FOREIGN KEY (project_id) REFERENCES audit_project(id) ON DELETE CASCADE
);

CREATE TABLE code_chunk (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_id UUID NOT NULL,
    file_path VARCHAR(1000) NOT NULL,
    symbol_name VARCHAR(500),
    endpoint VARCHAR(500),
    start_line INTEGER NOT NULL,
    end_line INTEGER NOT NULL,
    content TEXT NOT NULL,
    embedding TEXT NOT NULL,
    CONSTRAINT fk_code_chunk_task
        FOREIGN KEY (task_id) REFERENCES audit_task(id) ON DELETE CASCADE
);

CREATE TABLE finding (
    id UUID PRIMARY KEY,
    task_id UUID NOT NULL,
    type VARCHAR(50) NOT NULL,
    severity VARCHAR(20) NOT NULL,
    confidence VARCHAR(20) NOT NULL,
    title VARCHAR(500) NOT NULL,
    file_path VARCHAR(1000) NOT NULL,
    start_line INTEGER NOT NULL,
    end_line INTEGER NOT NULL,
    endpoint VARCHAR(500),
    description TEXT NOT NULL,
    evidence TEXT NOT NULL,
    remediation TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_finding_task
        FOREIGN KEY (task_id) REFERENCES audit_task(id) ON DELETE CASCADE
);
