ALTER TABLE code_chunk ADD COLUMN chunk_type VARCHAR(40) NOT NULL DEFAULT 'TEXT';
ALTER TABLE code_chunk ADD COLUMN parameters TEXT NOT NULL DEFAULT '';
ALTER TABLE code_chunk ADD COLUMN annotations TEXT NOT NULL DEFAULT '';
ALTER TABLE code_chunk ADD COLUMN called_symbols TEXT NOT NULL DEFAULT '';

CREATE TABLE agent_run (
    id UUID PRIMARY KEY,
    task_id UUID NOT NULL,
    agent_type VARCHAR(40) NOT NULL,
    target_chunk_id BIGINT,
    target_symbol VARCHAR(500),
    status VARCHAR(30) NOT NULL,
    step_count INTEGER NOT NULL DEFAULT 0,
    tool_call_count INTEGER NOT NULL DEFAULT 0,
    model_call_count INTEGER NOT NULL DEFAULT 0,
    summary TEXT,
    started_at TIMESTAMP WITH TIME ZONE NOT NULL,
    completed_at TIMESTAMP WITH TIME ZONE,
    CONSTRAINT fk_agent_run_task FOREIGN KEY (task_id) REFERENCES audit_task(id) ON DELETE CASCADE,
    CONSTRAINT fk_agent_run_chunk FOREIGN KEY (target_chunk_id) REFERENCES code_chunk(id) ON DELETE SET NULL
);

CREATE TABLE agent_event (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_id UUID NOT NULL,
    run_id UUID,
    agent_type VARCHAR(40) NOT NULL,
    event_type VARCHAR(40) NOT NULL,
    message TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_agent_event_task FOREIGN KEY (task_id) REFERENCES audit_task(id) ON DELETE CASCADE,
    CONSTRAINT fk_agent_event_run FOREIGN KEY (run_id) REFERENCES agent_run(id) ON DELETE CASCADE
);

CREATE TABLE audit_hypothesis (
    id UUID PRIMARY KEY,
    task_id UUID NOT NULL,
    run_id UUID NOT NULL,
    type VARCHAR(50) NOT NULL,
    status VARCHAR(40) NOT NULL,
    claim TEXT NOT NULL,
    primary_chunk_id BIGINT NOT NULL,
    evidence_chunk_ids TEXT NOT NULL,
    confidence VARCHAR(20) NOT NULL,
    critic_reason TEXT,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_hypothesis_task FOREIGN KEY (task_id) REFERENCES audit_task(id) ON DELETE CASCADE,
    CONSTRAINT fk_hypothesis_run FOREIGN KEY (run_id) REFERENCES agent_run(id) ON DELETE CASCADE,
    CONSTRAINT fk_hypothesis_chunk FOREIGN KEY (primary_chunk_id) REFERENCES code_chunk(id) ON DELETE CASCADE
);

CREATE TABLE ai_report_summary (
    task_id UUID PRIMARY KEY,
    executive_summary TEXT NOT NULL,
    coverage_summary TEXT NOT NULL,
    generated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_ai_report_task FOREIGN KEY (task_id) REFERENCES audit_task(id) ON DELETE CASCADE
);

CREATE INDEX idx_agent_run_task ON agent_run(task_id);
CREATE INDEX idx_agent_event_task_id ON agent_event(task_id, id);
CREATE INDEX idx_hypothesis_task ON audit_hypothesis(task_id, status);
